package analytics

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/ConfabulousDev/confab-web/internal/anthropic"
	"github.com/ConfabulousDev/confab-web/internal/openai"
)

// LLM vendors that can generate smart recaps, selected instance-wide by
// SMART_RECAP_LLM_PROVIDER. Called "LLM provider" because plain "provider"
// means the coding agent (Claude Code, Codex, ...) everywhere else.
const (
	LLMProviderAnthropic = "anthropic"
	LLMProviderOpenAI    = "openai"
)

// llmProviderOrDefault maps an empty vendor to Anthropic. Empty means unset
// config or a legacy smart recap row written before llm_provider existed —
// every such card was generated by Anthropic.
func llmProviderOrDefault(provider string) string {
	if provider == "" {
		return LLMProviderAnthropic
	}
	return provider
}

// SmartRecapLLMConfig is the vendor-dependent part of smart recap configuration.
type SmartRecapLLMConfig struct {
	Provider   string // LLMProviderAnthropic or LLMProviderOpenAI
	APIKey     string // the active vendor's API key
	Model      string // SMART_RECAP_MODEL
	MissingVar string // first missing required env var; empty when complete
}

// ResolveSmartRecapLLMConfig reads SMART_RECAP_LLM_PROVIDER (unset → anthropic),
// the active vendor's API key (ANTHROPIC_API_KEY or OPENAI_API_KEY), and
// SMART_RECAP_MODEL. An unrecognized provider returns an error, regardless of
// SMART_RECAP_ENABLED; callers treat it as fatal. Missing key/model is not an
// error — it is reported via MissingVar so callers can disable the feature.
// Shared by the API server and the worker.
func ResolveSmartRecapLLMConfig(getenv func(string) string) (SmartRecapLLMConfig, error) {
	provider := strings.TrimSpace(getenv("SMART_RECAP_LLM_PROVIDER"))
	var keyVar string
	switch provider {
	case "", LLMProviderAnthropic:
		provider = LLMProviderAnthropic
		keyVar = "ANTHROPIC_API_KEY"
	case LLMProviderOpenAI:
		keyVar = "OPENAI_API_KEY"
	default:
		return SmartRecapLLMConfig{}, fmt.Errorf("invalid SMART_RECAP_LLM_PROVIDER %q: must be %q or %q",
			provider, LLMProviderAnthropic, LLMProviderOpenAI)
	}

	cfg := SmartRecapLLMConfig{
		Provider: provider,
		APIKey:   getenv(keyVar),
		Model:    getenv("SMART_RECAP_MODEL"),
	}
	switch {
	case cfg.APIKey == "":
		cfg.MissingVar = keyVar
	case cfg.Model == "":
		cfg.MissingVar = "SMART_RECAP_MODEL"
	}
	return cfg, nil
}

// recapLLMRequest is a vendor-neutral smart recap generation request.
type recapLLMRequest struct {
	Model           string
	System          string
	User            string
	MaxOutputTokens int
}

// recapLLMResponse carries the raw JSON text and token usage.
type recapLLMResponse struct {
	Text         string
	InputTokens  int
	OutputTokens int
}

// recapLLM is the seam between SmartRecapAnalyzer and an LLM vendor.
type recapLLM interface {
	Generate(ctx context.Context, req recapLLMRequest) (recapLLMResponse, error)
}

// newRecapLLM builds the client for a vendor. baseURL overrides the vendor's
// API base URL when non-empty (TEST_SMART_RECAP_BASE_URL).
func newRecapLLM(provider, apiKey, baseURL string) (recapLLM, error) {
	switch provider {
	case LLMProviderAnthropic:
		var opts []anthropic.ClientOption
		if baseURL != "" {
			opts = append(opts, anthropic.WithBaseURL(baseURL))
		}
		return anthropicRecapLLM{client: anthropic.NewClient(apiKey, opts...)}, nil
	case LLMProviderOpenAI:
		var opts []openai.ClientOption
		if baseURL != "" {
			opts = append(opts, openai.WithBaseURL(baseURL))
		}
		return openaiRecapLLM{client: openai.NewClient(apiKey, opts...)}, nil
	default:
		return nil, fmt.Errorf("unknown smart recap LLM provider %q", provider)
	}
}

// anthropicRecapLLM calls the Anthropic Messages API with an assistant prefill.
type anthropicRecapLLM struct {
	client *anthropic.Client
}

func (a anthropicRecapLLM) Generate(ctx context.Context, req recapLLMRequest) (recapLLMResponse, error) {
	// Low temperature for mostly consistent output.
	// 0.25 allows slight variation on regeneration while staying focused.
	temperature := 0.25
	resp, err := a.client.CreateMessage(ctx, &anthropic.MessagesRequest{
		Model:       req.Model,
		MaxTokens:   req.MaxOutputTokens,
		Temperature: &temperature,
		System:      req.System,
		Messages: []anthropic.Message{
			{Role: "user", Content: req.User},
			// Prefill assistant response with "{" to force JSON output.
			// This prevents the model from role-playing as Claude Code when
			// analyzing transcripts that contain tool calls.
			{Role: "assistant", Content: "{"},
		},
	})
	if err != nil {
		return recapLLMResponse{}, err
	}
	// The API returns only the continuation after the prefilled "{".
	return recapLLMResponse{
		Text:         "{" + resp.GetTextContent(),
		InputTokens:  resp.Usage.InputTokens,
		OutputTokens: resp.Usage.OutputTokens,
	}, nil
}

// openaiRecapLLM calls the OpenAI Responses API with strict structured outputs.
type openaiRecapLLM struct {
	client *openai.Client
}

func (o openaiRecapLLM) Generate(ctx context.Context, req recapLLMRequest) (recapLLMResponse, error) {
	store := false
	resp, err := o.client.CreateResponse(ctx, &openai.ResponsesRequest{
		Model:           req.Model,
		Instructions:    req.System,
		Input:           req.User,
		MaxOutputTokens: req.MaxOutputTokens,
		// Recap is summarization/extraction. Reasoning tokens would also count
		// against the output cap. No temperature: GPT-5.x reasoning models reject it.
		Reasoning: &openai.Reasoning{Effort: "none"},
		// Don't retain transcripts on OpenAI's side (the API default keeps them 30 days).
		Store: &store,
		Text: &openai.TextConfig{Format: openai.TextFormat{
			Type:   "json_schema",
			Name:   "smart_recap",
			Strict: true,
			Schema: json.RawMessage(smartRecapJSONSchema),
		}},
	})
	if err != nil {
		return recapLLMResponse{}, err
	}
	if resp.Status != "completed" {
		reason := ""
		if resp.IncompleteDetails != nil {
			reason = resp.IncompleteDetails.Reason
		}
		return recapLLMResponse{}, fmt.Errorf("openai response not completed (status %q, reason %q)", resp.Status, reason)
	}
	if refusal := resp.Refusal(); refusal != "" {
		return recapLLMResponse{}, fmt.Errorf("openai refused smart recap request: %s", refusal)
	}
	text := resp.OutputText()
	if text == "" {
		return recapLLMResponse{}, errors.New("openai response has no output text")
	}
	return recapLLMResponse{
		Text:         text,
		InputTokens:  resp.Usage.InputTokens,
		OutputTokens: resp.Usage.OutputTokens,
	}, nil
}

// smartRecapAnnotatedListSchema is the schema for a list of AnnotatedItem.
// message_id is nullable rather than optional because strict mode requires
// every property to be listed in "required".
const smartRecapAnnotatedListSchema = `{
		"type": "array",
		"items": {
			"type": "object",
			"properties": {
				"text": {"type": "string"},
				"message_id": {"type": ["integer", "null"]}
			},
			"required": ["text", "message_id"],
			"additionalProperties": false
		}
	}`

// smartRecapJSONSchema is the strict JSON Schema for smart recap output, sent
// natively to OpenAI. It mirrors smartRecapOutputSchema (the prose version kept
// in the system prompt for every vendor) and the json tags of SmartRecapResult
// and AnnotatedItem. TestSmartRecapJSONSchema_MatchesResultStructs guards drift.
// Length and item-count limits are enforced by parseSmartRecapResponse instead.
const smartRecapJSONSchema = `{
	"type": "object",
	"properties": {
		"suggested_session_title": {"type": "string"},
		"recap": {"type": "string"},
		"went_well": ` + smartRecapAnnotatedListSchema + `,
		"went_bad": ` + smartRecapAnnotatedListSchema + `,
		"human_suggestions": ` + smartRecapAnnotatedListSchema + `,
		"environment_suggestions": ` + smartRecapAnnotatedListSchema + `,
		"default_context_suggestions": ` + smartRecapAnnotatedListSchema + `
	},
	"required": [
		"suggested_session_title",
		"recap",
		"went_well",
		"went_bad",
		"human_suggestions",
		"environment_suggestions",
		"default_context_suggestions"
	],
	"additionalProperties": false
}`
