import { useMemo, useState, useCallback } from 'react';
import type { TranscriptLine } from '@/types';
import { useKeyboardShortcut, useSpinner } from '@/hooks';
import { calculateTokenStats, calculateEstimatedCost, formatTokenCount, formatCost } from '@/utils/tokenStats';
import { calculateCompactionStats } from '@/utils/compactionStats';
import PageSidebar from '../PageSidebar';
import styles from './SessionStatsSidebar.module.css';

interface SessionStatsSidebarProps {
  messages: TranscriptLine[];
  loading?: boolean;
}

// Placeholder stats for non-token sections
const PLACEHOLDER_STATS = {
  duration: {
    total: '1h 23m',
    userWait: '47m 12s',
    assistant: '35m 48s',
  },
  userInputDelay: {
    n: 42,
    min: '1.2s',
    p50: '8.4s',
    p98: '1m 45s',
    max: '3m 12s',
  },
  compactionDelay: {
    n: 18,
    min: '0.8s',
    p50: '2.1s',
    max: '12.3s',
  },
};

// Placeholder tooltips
const TOOLTIPS = {
  cost: {
    estimated: 'Estimated API cost based on token usage and model pricing (assumes 5-minute prompt caching)',
  },
  tokens: {
    input: 'Total tokens sent to the model',
    output: 'Total tokens generated by the model',
    cacheCreated: 'Tokens written to cache for future use',
    cacheRead: 'Tokens served from cache (reduced cost)',
  },
  duration: {
    total: 'Total elapsed time for the session',
    userWait: 'Time spent waiting for user input',
    assistant: 'Time spent waiting for assistant responses',
  },
  userInputDelay: {
    n: 'Number of user input events measured',
    min: 'Shortest delay between assistant response and user input',
    p50: 'Median delay between assistant response and user input',
    p98: '98th percentile delay between assistant response and user input',
    max: 'Longest delay between assistant response and user input',
  },
  compactionDelay: {
    n: 'Number of compaction events measured',
    min: 'Shortest compaction processing time',
    p50: 'Median compaction processing time',
    max: 'Longest compaction processing time',
  },
  compaction: {
    total: 'Total number of context compaction events',
    auto: 'Compactions triggered automatically when context limit reached',
    manual: 'Compactions triggered manually by user',
  },
};

// Icons
const InfoIcon = (
  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <circle cx="12" cy="12" r="10" />
    <path d="M12 16v-4" />
    <path d="M12 8h.01" />
  </svg>
);

function SessionStatsSidebar({ messages, loading = false }: SessionStatsSidebarProps) {
  const tokenStats = useMemo(() => calculateTokenStats(messages), [messages]);
  const estimatedCost = useMemo(() => calculateEstimatedCost(messages), [messages]);
  const compactionStats = useMemo(() => calculateCompactionStats(messages), [messages]);
  const [showDebugStats, setShowDebugStats] = useState(false);
  const spinner = useSpinner(loading);

  // Hidden keyboard shortcut to toggle debug stats (Duration, User Input Delay, Compaction Delay)
  const handleToggleDebugStats = useCallback(() => {
    setShowDebugStats((prev) => !prev);
  }, []);
  useKeyboardShortcut('mod+shift+e', handleToggleDebugStats);

  // Helper to render a value or spinner when loading
  const renderValue = (value: string) => (loading ? spinner : value);

  return (
    <PageSidebar
      title="Session Stats"
      collapsible={false}
    >
      <div>
        {/* Tokens Section */}
        <div className={styles.section}>
          <div className={styles.sectionHeader}>Tokens</div>
          <div className={styles.statRow} title={TOOLTIPS.tokens.input}>
            <span className={styles.statLabel}>
              <span className={styles.statIcon}>→</span>
              Input
            </span>
            <span className={styles.statValue}>{renderValue(formatTokenCount(tokenStats.input))}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.tokens.output}>
            <span className={styles.statLabel}>
              <span className={styles.statIcon}>←</span>
              Output
            </span>
            <span className={styles.statValue}>{renderValue(formatTokenCount(tokenStats.output))}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.tokens.cacheCreated}>
            <span className={styles.statLabel}>
              <span className={styles.statIcon}>◇</span>
              Cache created
            </span>
            <span className={styles.statValue}>{renderValue(formatTokenCount(tokenStats.cacheCreated))}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.tokens.cacheRead}>
            <span className={styles.statLabel}>
              <span className={styles.statIcon}>◆</span>
              Cache read
            </span>
            <span className={styles.statValue}>{renderValue(formatTokenCount(tokenStats.cacheRead))}</span>
          </div>
        </div>

        {/* Cost Section */}
        <div className={styles.section}>
          <div className={styles.sectionHeader}>Cost</div>
          <div className={styles.statRow} title={TOOLTIPS.cost.estimated}>
            <span className={styles.statLabel}>
              <span className={styles.statIcon}>{InfoIcon}</span>
              Estimated
            </span>
            <span className={styles.statValue}>
              {renderValue(formatCost(estimatedCost))}
            </span>
          </div>
        </div>

        {/* Compaction Section */}
        <div className={styles.section}>
          <div className={styles.sectionHeader}>Compaction</div>
          <div className={styles.statRow} title={TOOLTIPS.compaction.total}>
            <span className={styles.statLabel}>Total</span>
            <span className={styles.statValue}>{renderValue(String(compactionStats.total))}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.compaction.auto}>
            <span className={styles.statLabel}>Auto</span>
            <span className={styles.statValue}>{renderValue(String(compactionStats.auto))}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.compaction.manual}>
            <span className={styles.statLabel}>Manual</span>
            <span className={styles.statValue}>{renderValue(String(compactionStats.manual))}</span>
          </div>
        </div>

        {/* Debug Stats - hidden by default, toggle with Cmd+Shift+D */}
        {showDebugStats && (
          <>
            {/* Duration Section */}
            <div className={styles.section}>
              <div className={styles.sectionHeader}>Duration</div>
              <div className={styles.statRow} title={TOOLTIPS.duration.total}>
                <span className={styles.statLabel}>
                  <span className={styles.statIcon}>⏱</span>
                  Total
                </span>
                <span className={styles.statValue}>{PLACEHOLDER_STATS.duration.total}</span>
              </div>
              <div className={styles.statRow} title={TOOLTIPS.duration.userWait}>
                <span className={styles.statLabel}>
                  <span className={styles.statIcon}>👤</span>
                  Await user
                </span>
                <span className={styles.statValue}>{PLACEHOLDER_STATS.duration.userWait}</span>
              </div>
              <div className={styles.statRow} title={TOOLTIPS.duration.assistant}>
                <span className={styles.statLabel}>
                  <span className={styles.statIcon}>🤖</span>
                  Await assistant
                </span>
                <span className={styles.statValue}>{PLACEHOLDER_STATS.duration.assistant}</span>
              </div>
            </div>

            {/* User Input Delay Section */}
            <div className={styles.section}>
              <div className={styles.sectionHeader}>User Input Delay</div>
              <div className={styles.statRow} title={TOOLTIPS.userInputDelay.n}>
                <span className={styles.statLabel}>#</span>
                <span className={styles.statValue}>{PLACEHOLDER_STATS.userInputDelay.n}</span>
              </div>
              <div className={styles.statRow} title={TOOLTIPS.userInputDelay.min}>
                <span className={styles.statLabel}>Min</span>
                <span className={styles.statValue}>{PLACEHOLDER_STATS.userInputDelay.min}</span>
              </div>
              <div className={styles.statRow} title={TOOLTIPS.userInputDelay.p50}>
                <span className={styles.statLabel}>Median</span>
                <span className={styles.statValue}>{PLACEHOLDER_STATS.userInputDelay.p50}</span>
              </div>
              <div className={styles.statRow} title={TOOLTIPS.userInputDelay.p98}>
                <span className={styles.statLabel}>P98</span>
                <span className={styles.statValue}>{PLACEHOLDER_STATS.userInputDelay.p98}</span>
              </div>
              <div className={styles.statRow} title={TOOLTIPS.userInputDelay.max}>
                <span className={styles.statLabel}>Max</span>
                <span className={styles.statValue}>{PLACEHOLDER_STATS.userInputDelay.max}</span>
              </div>
            </div>

            {/* Compaction Delay Section */}
            <div className={styles.section}>
              <div className={styles.sectionHeader}>Compaction Delay</div>
              <div className={styles.statRow} title={TOOLTIPS.compactionDelay.n}>
                <span className={styles.statLabel}>#</span>
                <span className={styles.statValue}>{PLACEHOLDER_STATS.compactionDelay.n}</span>
              </div>
              <div className={styles.statRow} title={TOOLTIPS.compactionDelay.min}>
                <span className={styles.statLabel}>Min</span>
                <span className={styles.statValue}>{PLACEHOLDER_STATS.compactionDelay.min}</span>
              </div>
              <div className={styles.statRow} title={TOOLTIPS.compactionDelay.p50}>
                <span className={styles.statLabel}>Median</span>
                <span className={styles.statValue}>{PLACEHOLDER_STATS.compactionDelay.p50}</span>
              </div>
              <div className={styles.statRow} title={TOOLTIPS.compactionDelay.max}>
                <span className={styles.statLabel}>Max</span>
                <span className={styles.statValue}>{PLACEHOLDER_STATS.compactionDelay.max}</span>
              </div>
            </div>
          </>
        )}

      </div>
    </PageSidebar>
  );
}

export default SessionStatsSidebar;
