import { useState, useEffect, useCallback } from 'react';
import { analyticsAPI, type SessionAnalytics } from '@/services/api';
import { formatTokenCount, formatCost } from '@/utils/tokenStats';
import { formatResponseTime } from '@/utils/compactionStats';
import styles from './SessionAnalyticsPanel.module.css';

interface SessionAnalyticsPanelProps {
  sessionId: string;
  /** Current total lines in the session (for staleness detection) */
  totalLines: number;
  /** For Storybook: pass analytics directly instead of fetching from API */
  initialAnalytics?: SessionAnalytics;
}

const TOOLTIPS = {
  source: 'Server-computed analytics from cached JSONL parsing. Updates when session syncs new data.',
  cost: {
    estimated: 'Estimated API cost based on token usage and model pricing (assumes 5-minute prompt caching)',
  },
  tokens: {
    input: 'Total tokens sent to the model',
    output: 'Total tokens generated by the model',
    cacheCreated: 'Tokens written to cache for future use',
    cacheRead: 'Tokens served from cache (reduced cost)',
  },
  compaction: {
    auto: 'Compactions triggered automatically when context limit reached',
    manual: 'Compactions triggered manually by user',
    avgCompactionTime: 'Average time for server-side summarization (auto compactions only)',
  },
};

// Icons (matching sidebar style)
const InfoIcon = (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <circle cx="12" cy="12" r="10" />
    <path d="M12 16v-4" />
    <path d="M12 8h.01" />
  </svg>
);

const ServerIcon = (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <rect x="2" y="2" width="20" height="8" rx="2" ry="2"/>
    <rect x="2" y="14" width="20" height="8" rx="2" ry="2"/>
    <line x1="6" y1="6" x2="6.01" y2="6"/>
    <line x1="6" y1="18" x2="6.01" y2="18"/>
  </svg>
);

const RefreshIcon = (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <path d="M21 2v6h-6" />
    <path d="M3 12a9 9 0 0 1 15-6.7L21 8" />
    <path d="M3 22v-6h6" />
    <path d="M21 12a9 9 0 0 1-15 6.7L3 16" />
  </svg>
);

function SessionAnalyticsPanel({ sessionId, totalLines, initialAnalytics }: SessionAnalyticsPanelProps) {
  const [analytics, setAnalytics] = useState<SessionAnalytics | null>(initialAnalytics ?? null);
  const [loading, setLoading] = useState(!initialAnalytics);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchAnalytics = useCallback(async (isRefresh = false) => {
    if (initialAnalytics !== undefined) return;

    try {
      if (isRefresh) {
        setRefreshing(true);
      } else {
        setLoading(true);
      }
      setError(null);
      const data = await analyticsAPI.get(sessionId);
      setAnalytics(data);
    } catch (err) {
      console.error('Failed to fetch analytics:', err);
      setError(err instanceof Error ? err.message : 'Failed to load analytics');
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [sessionId, initialAnalytics]);

  useEffect(() => {
    fetchAnalytics();
  }, [fetchAnalytics]);

  // Calculate staleness (disable refresh in Storybook mode where initialAnalytics is provided)
  const computedLines = analytics?.computed_lines ?? 0;
  const newLines = totalLines - computedLines;
  const isStale = newLines > 0;
  const canRefresh = isStale && initialAnalytics === undefined;

  const handleRefresh = useCallback(() => {
    fetchAnalytics(true);
  }, [fetchAnalytics]);

  if (loading) {
    return (
      <div className={styles.panel}>
        <div className={styles.loading}>Loading analytics...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className={styles.panel}>
        <div className={styles.error}>
          <strong>Error:</strong> {error}
          <button className={styles.retryButton} onClick={() => fetchAnalytics()}>
            Retry
          </button>
        </div>
      </div>
    );
  }

  if (!analytics) {
    return (
      <div className={styles.panel}>
        <div className={styles.empty}>No analytics data available</div>
      </div>
    );
  }

  const cost = parseFloat(analytics.cost.estimated_usd);

  return (
    <div className={styles.panel}>
      <div className={styles.header}>
        <div className={styles.headerLeft}>
          <h2 className={styles.title}>Session Analytics</h2>
          <div className={styles.source} title={TOOLTIPS.source}>
            {ServerIcon}
            <span>Server-computed</span>
          </div>
        </div>
        <button
          className={`${styles.refreshButton} ${canRefresh ? styles.refreshStale : ''} ${refreshing ? styles.refreshing : ''}`}
          onClick={handleRefresh}
          disabled={!canRefresh || refreshing}
          title={isStale ? `${newLines} new lines available` : 'Analytics up to date'}
        >
          {RefreshIcon}
          {isStale ? `+${newLines} lines` : 'Up to date'}
        </button>
      </div>

      <div className={styles.grid}>
        {/* Tokens Section */}
        <div className={styles.card}>
          <div className={styles.cardHeader}>Tokens</div>
          <div className={styles.cardContent}>
            <div className={styles.statRow} title={TOOLTIPS.tokens.input}>
              <span className={styles.statLabel}>
                <span className={styles.statIcon}>&#8594;</span>
                Input
              </span>
              <span className={styles.statValue}>{formatTokenCount(analytics.tokens.input)}</span>
            </div>
            <div className={styles.statRow} title={TOOLTIPS.tokens.output}>
              <span className={styles.statLabel}>
                <span className={styles.statIcon}>&#8592;</span>
                Output
              </span>
              <span className={styles.statValue}>{formatTokenCount(analytics.tokens.output)}</span>
            </div>
            <div className={styles.statRow} title={TOOLTIPS.tokens.cacheCreated}>
              <span className={styles.statLabel}>
                <span className={styles.statIcon}>&#9671;</span>
                Cache created
              </span>
              <span className={styles.statValue}>{formatTokenCount(analytics.tokens.cache_creation)}</span>
            </div>
            <div className={styles.statRow} title={TOOLTIPS.tokens.cacheRead}>
              <span className={styles.statLabel}>
                <span className={styles.statIcon}>&#9670;</span>
                Cache read
              </span>
              <span className={styles.statValue}>{formatTokenCount(analytics.tokens.cache_read)}</span>
            </div>
          </div>
        </div>

        {/* Cost Section */}
        <div className={styles.card}>
          <div className={styles.cardHeader}>Cost</div>
          <div className={styles.cardContent}>
            <div className={styles.statRow} title={TOOLTIPS.cost.estimated}>
              <span className={styles.statLabel}>
                <span className={styles.statIcon}>{InfoIcon}</span>
                Estimated
              </span>
              <span className={`${styles.statValue} ${styles.cost}`}>
                {formatCost(cost)}
              </span>
            </div>
          </div>
        </div>

        {/* Compaction Section */}
        <div className={styles.card}>
          <div className={styles.cardHeader}>Compaction</div>
          <div className={styles.cardContent}>
            <div className={styles.statRow} title={TOOLTIPS.compaction.auto}>
              <span className={styles.statLabel}>Auto</span>
              <span className={styles.statValue}>{analytics.compaction.auto}</span>
            </div>
            <div className={styles.statRow} title={TOOLTIPS.compaction.manual}>
              <span className={styles.statLabel}>Manual</span>
              <span className={styles.statValue}>{analytics.compaction.manual}</span>
            </div>
            <div className={styles.statRow} title={TOOLTIPS.compaction.avgCompactionTime}>
              <span className={styles.statLabel}>Avg time (auto)</span>
              <span className={styles.statValue}>
                {formatResponseTime(analytics.compaction.avg_time_ms ?? null)}
              </span>
            </div>
          </div>
        </div>
      </div>

      <div className={styles.footer}>
        <p className={styles.footerNote}>
          These metrics are computed server-side from the JSONL transcript and cached for performance.
          Compare with the sidebar&apos;s real-time client-computed stats.
        </p>
      </div>
    </div>
  );
}

export default SessionAnalyticsPanel;
