import { useAnalyticsPolling } from '@/hooks/useAnalyticsPolling';
import { RelativeTime } from '@/components/RelativeTime';
import type { SessionAnalytics, GitHubLink } from '@/schemas/api';
import { formatTokenCount, formatCost } from '@/utils/tokenStats';
import { formatResponseTime } from '@/utils/compactionStats';
import GitHubLinksCard from './GitHubLinksCard';
import styles from './SessionSummaryPanel.module.css';

interface SessionSummaryPanelProps {
  sessionId: string;
  isOwner: boolean;
  /** For Storybook: pass analytics directly instead of fetching from API */
  initialAnalytics?: SessionAnalytics;
  /** For Storybook: pass GitHub links directly instead of fetching from API */
  initialGithubLinks?: GitHubLink[];
}

const TOOLTIPS = {
  cost: {
    estimated: 'Estimated API cost based on token usage and model pricing (assumes 5-minute prompt caching)',
  },
  tokens: {
    input: 'Total tokens sent to the model',
    output: 'Total tokens generated by the model',
    cacheCreated: 'Tokens written to cache for future use',
    cacheRead: 'Tokens served from cache (reduced cost)',
  },
  compaction: {
    auto: 'Compactions triggered automatically when context limit reached',
    manual: 'Compactions triggered manually by user',
    avgCompactionTime: 'Average time for server-side summarization (auto compactions only)',
  },
};

// Icons
const InfoIcon = (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <circle cx="12" cy="12" r="10" />
    <path d="M12 16v-4" />
    <path d="M12 8h.01" />
  </svg>
);

function SessionSummaryPanel({ sessionId, isOwner, initialAnalytics, initialGithubLinks }: SessionSummaryPanelProps) {
  // Use polling hook for live updates (disabled in Storybook mode)
  const { analytics: polledAnalytics, loading, error } = useAnalyticsPolling(
    sessionId,
    initialAnalytics === undefined // Disable polling in Storybook mode
  );

  // Use initial analytics for Storybook, polled analytics for real usage
  const analytics = initialAnalytics ?? polledAnalytics;

  const cost = analytics ? parseFloat(analytics.cost.estimated_usd) : 0;

  // Render analytics cards content based on state
  const renderAnalyticsCards = () => {
    if (loading && !analytics) {
      return (
        <div className={styles.card}>
          <div className={styles.cardContent}>
            <div className={styles.loading}>Loading analytics...</div>
          </div>
        </div>
      );
    }

    if (error && !analytics) {
      return (
        <div className={styles.card}>
          <div className={styles.cardContent}>
            <div className={styles.analyticsError}>Failed to load analytics</div>
          </div>
        </div>
      );
    }

    if (!analytics) {
      return (
        <div className={styles.card}>
          <div className={styles.cardContent}>
            <div className={styles.analyticsEmpty}>No analytics available</div>
          </div>
        </div>
      );
    }

    return (
      <>
        {/* Tokens Section */}
        <div className={styles.card}>
          <div className={styles.cardHeader}>Tokens</div>
          <div className={styles.cardContent}>
            <div className={styles.statRow} title={TOOLTIPS.tokens.input}>
              <span className={styles.statLabel}>
                <span className={styles.statIcon}>&#8594;</span>
                Input
              </span>
              <span className={styles.statValue}>{formatTokenCount(analytics.tokens.input)}</span>
            </div>
            <div className={styles.statRow} title={TOOLTIPS.tokens.output}>
              <span className={styles.statLabel}>
                <span className={styles.statIcon}>&#8592;</span>
                Output
              </span>
              <span className={styles.statValue}>{formatTokenCount(analytics.tokens.output)}</span>
            </div>
            <div className={styles.statRow} title={TOOLTIPS.tokens.cacheCreated}>
              <span className={styles.statLabel}>
                <span className={styles.statIcon}>&#9671;</span>
                Cache created
              </span>
              <span className={styles.statValue}>{formatTokenCount(analytics.tokens.cache_creation)}</span>
            </div>
            <div className={styles.statRow} title={TOOLTIPS.tokens.cacheRead}>
              <span className={styles.statLabel}>
                <span className={styles.statIcon}>&#9670;</span>
                Cache read
              </span>
              <span className={styles.statValue}>{formatTokenCount(analytics.tokens.cache_read)}</span>
            </div>
          </div>
        </div>

        {/* Cost Section */}
        <div className={styles.card}>
          <div className={styles.cardHeader}>Cost</div>
          <div className={styles.cardContent}>
            <div className={styles.statRow} title={TOOLTIPS.cost.estimated}>
              <span className={styles.statLabel}>
                <span className={styles.statIcon}>{InfoIcon}</span>
                Estimated
              </span>
              <span className={`${styles.statValue} ${styles.cost}`}>
                {formatCost(cost)}
              </span>
            </div>
          </div>
        </div>

        {/* Compaction Section */}
        <div className={styles.card}>
          <div className={styles.cardHeader}>Compaction</div>
          <div className={styles.cardContent}>
            <div className={styles.statRow} title={TOOLTIPS.compaction.auto}>
              <span className={styles.statLabel}>Auto</span>
              <span className={styles.statValue}>{analytics.compaction.auto}</span>
            </div>
            <div className={styles.statRow} title={TOOLTIPS.compaction.manual}>
              <span className={styles.statLabel}>Manual</span>
              <span className={styles.statValue}>{analytics.compaction.manual}</span>
            </div>
            <div className={styles.statRow} title={TOOLTIPS.compaction.avgCompactionTime}>
              <span className={styles.statLabel}>Avg time (auto)</span>
              <span className={styles.statValue}>
                {formatResponseTime(analytics.compaction.avg_time_ms ?? null)}
              </span>
            </div>
          </div>
        </div>
      </>
    );
  };

  return (
    <div className={styles.panel}>
      <div className={styles.header}>
        <h2 className={styles.title}>Session Summary</h2>
        {analytics && (
          <div className={styles.lastUpdated} title="When analytics were last computed">
            Updated <RelativeTime date={analytics.computed_at} />
          </div>
        )}
      </div>

      <div className={styles.grid}>
        {/* GitHub Links - always rendered, independent of analytics */}
        <GitHubLinksCard
          sessionId={sessionId}
          isOwner={isOwner}
          initialLinks={initialGithubLinks}
        />

        {renderAnalyticsCards()}
      </div>
    </div>
  );
}

export default SessionSummaryPanel;
