import { useMemo } from 'react';
import type { TranscriptLine } from '@/types';
import { useSpinner } from '@/hooks';
import { calculateTokenStats, calculateEstimatedCost, formatTokenCount, formatCost } from '@/utils/tokenStats';
import { calculateCompactionStats, formatResponseTime } from '@/utils/compactionStats';
import PageSidebar from '../PageSidebar';
import styles from './SessionStatsSidebar.module.css';

interface SessionStatsSidebarProps {
  messages: TranscriptLine[];
  loading?: boolean;
}

const TOOLTIPS = {
  cost: {
    estimated: 'Estimated API cost based on token usage and model pricing (assumes 5-minute prompt caching)',
  },
  tokens: {
    input: 'Total tokens sent to the model',
    output: 'Total tokens generated by the model',
    cacheCreated: 'Tokens written to cache for future use',
    cacheRead: 'Tokens served from cache (reduced cost)',
  },
  compaction: {
    auto: 'Compactions triggered automatically when context limit reached',
    manual: 'Compactions triggered manually by user',
    avgCompactionTime: 'Average time for server-side summarization (auto compactions only)',
  },
};

// Icons
const InfoIcon = (
  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <circle cx="12" cy="12" r="10" />
    <path d="M12 16v-4" />
    <path d="M12 8h.01" />
  </svg>
);

function SessionStatsSidebar({ messages, loading = false }: SessionStatsSidebarProps) {
  const tokenStats = useMemo(() => calculateTokenStats(messages), [messages]);
  const estimatedCost = useMemo(() => calculateEstimatedCost(messages), [messages]);
  const compactionStats = useMemo(() => calculateCompactionStats(messages), [messages]);
  const spinner = useSpinner(loading);

  // Helper to render a value or spinner when loading
  const renderValue = (value: string) => (loading ? spinner : value);

  return (
    <PageSidebar
      title="Session Stats"
      collapsible={false}
    >
      <div>
        {/* Tokens Section */}
        <div className={styles.section}>
          <div className={styles.sectionHeader}>Tokens</div>
          <div className={styles.statRow} title={TOOLTIPS.tokens.input}>
            <span className={styles.statLabel}>
              <span className={styles.statIcon}>→</span>
              Input
            </span>
            <span className={styles.statValue}>{renderValue(formatTokenCount(tokenStats.input))}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.tokens.output}>
            <span className={styles.statLabel}>
              <span className={styles.statIcon}>←</span>
              Output
            </span>
            <span className={styles.statValue}>{renderValue(formatTokenCount(tokenStats.output))}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.tokens.cacheCreated}>
            <span className={styles.statLabel}>
              <span className={styles.statIcon}>◇</span>
              Cache created
            </span>
            <span className={styles.statValue}>{renderValue(formatTokenCount(tokenStats.cacheCreated))}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.tokens.cacheRead}>
            <span className={styles.statLabel}>
              <span className={styles.statIcon}>◆</span>
              Cache read
            </span>
            <span className={styles.statValue}>{renderValue(formatTokenCount(tokenStats.cacheRead))}</span>
          </div>
        </div>

        {/* Cost Section */}
        <div className={styles.section}>
          <div className={styles.sectionHeader}>Cost</div>
          <div className={styles.statRow} title={TOOLTIPS.cost.estimated}>
            <span className={styles.statLabel}>
              <span className={styles.statIcon}>{InfoIcon}</span>
              Estimated
            </span>
            <span className={styles.statValue}>
              {renderValue(formatCost(estimatedCost))}
            </span>
          </div>
        </div>

        {/* Compaction Section */}
        <div className={styles.section}>
          <div className={styles.sectionHeader}>Compaction</div>
          <div className={styles.statRow} title={TOOLTIPS.compaction.auto}>
            <span className={styles.statLabel}>Auto</span>
            <span className={styles.statValue}>{renderValue(String(compactionStats.auto))}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.compaction.manual}>
            <span className={styles.statLabel}>Manual</span>
            <span className={styles.statValue}>{renderValue(String(compactionStats.manual))}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.compaction.avgCompactionTime}>
            <span className={styles.statLabel}>Avg time (auto)</span>
            <span className={styles.statValue}>{renderValue(formatResponseTime(compactionStats.avgCompactionTimeMs))}</span>
          </div>
        </div>
      </div>
    </PageSidebar>
  );
}

export default SessionStatsSidebar;
