import PageSidebar from '../PageSidebar';
import styles from './SessionStatsSidebar.module.css';

type SessionStatsSidebarProps = Record<string, never>;

// Placeholder stats - these will be replaced with real data later
const PLACEHOLDER_STATS = {
  cost: {
    estimated: '$4.23',
  },
  tokens: {
    input: '145.9k',
    output: '23.5k',
    cached: '89.2k',
    total: '169.3k',
  },
  duration: {
    total: '1h 23m',
    userWait: '47m 12s',
    assistant: '35m 48s',
  },
  userInputDelay: {
    n: 42,
    min: '1.2s',
    p50: '8.4s',
    p98: '1m 45s',
    max: '3m 12s',
  },
  compactionDelay: {
    n: 18,
    min: '0.8s',
    p50: '2.1s',
    max: '12.3s',
  },
};

// Placeholder tooltips
const TOOLTIPS = {
  cost: {
    estimated: 'Estimated cost based on token usage and model pricing',
  },
  tokens: {
    input: 'Total tokens sent to the model',
    output: 'Total tokens generated by the model',
    cached: 'Tokens served from cache (reduced cost)',
    total: 'Total tokens processed in this session',
  },
  duration: {
    total: 'Total elapsed time for the session',
    userWait: 'Time spent waiting for user input',
    assistant: 'Time spent waiting for assistant responses',
  },
  userInputDelay: {
    n: 'Number of user input events measured',
    min: 'Shortest delay between assistant response and user input',
    p50: 'Median delay between assistant response and user input',
    p98: '98th percentile delay between assistant response and user input',
    max: 'Longest delay between assistant response and user input',
  },
  compactionDelay: {
    n: 'Number of compaction events measured',
    min: 'Shortest compaction processing time',
    p50: 'Median compaction processing time',
    max: 'Longest compaction processing time',
  },
};

// Icons
const InfoIcon = (
  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <circle cx="12" cy="12" r="10" />
    <path d="M12 16v-4" />
    <path d="M12 8h.01" />
  </svg>
);

function SessionStatsSidebar(_props: SessionStatsSidebarProps) {
  return (
    <PageSidebar
      title="Session Stats"
      collapsible={false}
    >
      <div>
        {/* Tokens Section */}
        <div className={styles.section}>
          <div className={styles.sectionHeader}>Tokens</div>
          <div className={styles.statRow} title={TOOLTIPS.tokens.input}>
            <span className={styles.statLabel}>
              <span className={styles.statIcon}>→</span>
              Input
            </span>
            <span className={styles.statValue}>{PLACEHOLDER_STATS.tokens.input}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.tokens.output}>
            <span className={styles.statLabel}>
              <span className={styles.statIcon}>←</span>
              Output
            </span>
            <span className={styles.statValue}>{PLACEHOLDER_STATS.tokens.output}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.tokens.cached}>
            <span className={styles.statLabel}>
              <span className={styles.statIcon}>◇</span>
              Cached
            </span>
            <span className={styles.statValue}>{PLACEHOLDER_STATS.tokens.cached}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.tokens.total}>
            <span className={styles.statLabel}>
              <span className={styles.statIcon}>■</span>
              Total
            </span>
            <span className={styles.statValue}>{PLACEHOLDER_STATS.tokens.total}</span>
          </div>
        </div>

        {/* Cost Section */}
        <div className={styles.section}>
          <div className={styles.sectionHeader}>Cost</div>
          <div className={styles.statRow} title={TOOLTIPS.cost.estimated}>
            <span className={styles.statLabel}>
              <span className={styles.statIcon}>{InfoIcon}</span>
              Estimated
            </span>
            <span className={styles.statValue}>
              {PLACEHOLDER_STATS.cost.estimated}
            </span>
          </div>
        </div>

        {/* Duration Section */}
        <div className={styles.section}>
          <div className={styles.sectionHeader}>Duration</div>
          <div className={styles.statRow} title={TOOLTIPS.duration.total}>
            <span className={styles.statLabel}>
              <span className={styles.statIcon}>⏱</span>
              Total
            </span>
            <span className={styles.statValue}>{PLACEHOLDER_STATS.duration.total}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.duration.userWait}>
            <span className={styles.statLabel}>
              <span className={styles.statIcon}>👤</span>
              Await user
            </span>
            <span className={styles.statValue}>{PLACEHOLDER_STATS.duration.userWait}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.duration.assistant}>
            <span className={styles.statLabel}>
              <span className={styles.statIcon}>🤖</span>
              Await assistant
            </span>
            <span className={styles.statValue}>{PLACEHOLDER_STATS.duration.assistant}</span>
          </div>
        </div>

        {/* User Input Delay Section */}
        <div className={styles.section}>
          <div className={styles.sectionHeader}>User Input Delay</div>
          <div className={styles.statRow} title={TOOLTIPS.userInputDelay.n}>
            <span className={styles.statLabel}>#</span>
            <span className={styles.statValue}>{PLACEHOLDER_STATS.userInputDelay.n}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.userInputDelay.min}>
            <span className={styles.statLabel}>Min</span>
            <span className={styles.statValue}>{PLACEHOLDER_STATS.userInputDelay.min}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.userInputDelay.p50}>
            <span className={styles.statLabel}>Median</span>
            <span className={styles.statValue}>{PLACEHOLDER_STATS.userInputDelay.p50}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.userInputDelay.p98}>
            <span className={styles.statLabel}>P98</span>
            <span className={styles.statValue}>{PLACEHOLDER_STATS.userInputDelay.p98}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.userInputDelay.max}>
            <span className={styles.statLabel}>Max</span>
            <span className={styles.statValue}>{PLACEHOLDER_STATS.userInputDelay.max}</span>
          </div>
        </div>

        {/* Compaction Delay Section */}
        <div className={styles.section}>
          <div className={styles.sectionHeader}>Compaction Delay</div>
          <div className={styles.statRow} title={TOOLTIPS.compactionDelay.n}>
            <span className={styles.statLabel}>#</span>
            <span className={styles.statValue}>{PLACEHOLDER_STATS.compactionDelay.n}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.compactionDelay.min}>
            <span className={styles.statLabel}>Min</span>
            <span className={styles.statValue}>{PLACEHOLDER_STATS.compactionDelay.min}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.compactionDelay.p50}>
            <span className={styles.statLabel}>Median</span>
            <span className={styles.statValue}>{PLACEHOLDER_STATS.compactionDelay.p50}</span>
          </div>
          <div className={styles.statRow} title={TOOLTIPS.compactionDelay.max}>
            <span className={styles.statLabel}>Max</span>
            <span className={styles.statValue}>{PLACEHOLDER_STATS.compactionDelay.max}</span>
          </div>
        </div>

      </div>
    </PageSidebar>
  );
}

export default SessionStatsSidebar;
