import { CardWrapper, StatRow, CardLoading } from './Card';
import { formatTokenCount, formatCost } from '@/utils/tokenStats';
import type { TokensCardData } from '@/schemas/api';
import type { CardProps } from './types';
import styles from '../SessionSummaryPanel.module.css';

const TOOLTIPS = {
  input: 'Total tokens sent to the model',
  output: 'Total tokens generated by the model',
  cacheCreated: 'Tokens written to cache for future use',
  cacheRead: 'Tokens served from cache (reduced cost)',
  cost: 'Estimated API cost based on token usage and model pricing (assumes 5-minute prompt caching)',
};

const CostIcon = (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <circle cx="12" cy="12" r="10" />
    <path d="M12 16v-4" />
    <path d="M12 8h.01" />
  </svg>
);

export function TokensCard({ data, loading }: CardProps<TokensCardData>) {
  if (loading && !data) {
    return (
      <CardWrapper title="Tokens">
        <CardLoading />
      </CardWrapper>
    );
  }

  if (!data) return null;

  const cost = parseFloat(data.estimated_usd);

  return (
    <CardWrapper title="Tokens">
      <StatRow
        label="Input"
        value={formatTokenCount(data.input)}
        icon={<span>&#8594;</span>}
        tooltip={TOOLTIPS.input}
      />
      <StatRow
        label="Output"
        value={formatTokenCount(data.output)}
        icon={<span>&#8592;</span>}
        tooltip={TOOLTIPS.output}
      />
      <StatRow
        label="Cache created"
        value={formatTokenCount(data.cache_creation)}
        icon={<span>&#9671;</span>}
        tooltip={TOOLTIPS.cacheCreated}
      />
      <StatRow
        label="Cache read"
        value={formatTokenCount(data.cache_read)}
        icon={<span>&#9670;</span>}
        tooltip={TOOLTIPS.cacheRead}
      />
      <StatRow
        label="Estimated cost"
        value={formatCost(cost)}
        icon={CostIcon}
        tooltip={TOOLTIPS.cost}
        valueClassName={styles.cost}
      />
    </CardWrapper>
  );
}
