import { CardWrapper, StatRow, CardLoading } from './Card';
import { formatTokenCount } from '@/utils/tokenStats';
import type { TokensCardData } from '@/schemas/api';
import type { CardProps } from './types';

const TOOLTIPS = {
  input: 'Total tokens sent to the model',
  output: 'Total tokens generated by the model',
  cacheCreated: 'Tokens written to cache for future use',
  cacheRead: 'Tokens served from cache (reduced cost)',
};

export function TokensCard({ data, loading }: CardProps<TokensCardData>) {
  if (loading && !data) {
    return (
      <CardWrapper title="Tokens">
        <CardLoading />
      </CardWrapper>
    );
  }

  if (!data) return null;

  return (
    <CardWrapper title="Tokens">
      <StatRow
        label="Input"
        value={formatTokenCount(data.input)}
        icon={<span>&#8594;</span>}
        tooltip={TOOLTIPS.input}
      />
      <StatRow
        label="Output"
        value={formatTokenCount(data.output)}
        icon={<span>&#8592;</span>}
        tooltip={TOOLTIPS.output}
      />
      <StatRow
        label="Cache created"
        value={formatTokenCount(data.cache_creation)}
        icon={<span>&#9671;</span>}
        tooltip={TOOLTIPS.cacheCreated}
      />
      <StatRow
        label="Cache read"
        value={formatTokenCount(data.cache_read)}
        icon={<span>&#9670;</span>}
        tooltip={TOOLTIPS.cacheRead}
      />
    </CardWrapper>
  );
}
