import { CardWrapper, StatRow, CardLoading, CardError } from './Card';
import { formatTokenCount, formatCost } from '@/utils/tokenStats';
import {
  TokenIcon,
  DollarIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  DiamondOutlineIcon,
  DiamondFilledIcon,
  ZapIcon,
} from '@/components/icons';
import type { TokensCardData } from '@/schemas/api';
import type { CardProps } from './types';
import styles from '../SessionSummaryPanel.module.css';

const TOOLTIPS = {
  input: 'Total tokens sent to the model',
  output: 'Total tokens generated by the model',
  cacheCreated: 'Tokens written to cache for future use',
  cacheRead: 'Tokens served from cache (reduced cost)',
  cost: 'Estimated API cost based on token usage and model pricing (assumes 5-minute prompt caching)',
  fastCost: 'Cost from turns using fast mode (6x multiplier)',
};

export function TokensCard({ data, loading, error }: CardProps<TokensCardData>) {
  if (error && !data) {
    return <CardError title="Tokens" error={error} icon={TokenIcon} />;
  }

  if (loading && !data) {
    return (
      <CardWrapper title="Tokens" icon={TokenIcon}>
        <CardLoading />
      </CardWrapper>
    );
  }

  if (!data) return null;

  const cost = parseFloat(data.estimated_usd);
  const isZeroCost = cost === 0;
  const hasFastMode = data.fast_turns != null;

  return (
    <CardWrapper title="Tokens" icon={TokenIcon}>
      <StatRow
        label="Estimated cost"
        value={formatCost(cost)}
        icon={DollarIcon}
        tooltip={isZeroCost ? 'Cost unavailable — session may use models not yet in the pricing table' : TOOLTIPS.cost}
        valueClassName={isZeroCost ? styles.costWarning : styles.cost}
      />
      {hasFastMode && (
        <StatRow
          label="Fast mode"
          value={formatCost(parseFloat(data.fast_cost_usd!))}
          icon={ZapIcon}
          tooltip={TOOLTIPS.fastCost}
          valueClassName={styles.costFast}
        />
      )}
      <StatRow
        label="Input"
        value={formatTokenCount(data.input)}
        icon={ArrowRightIcon}
        tooltip={TOOLTIPS.input}
      />
      <StatRow
        label="Output"
        value={formatTokenCount(data.output)}
        icon={ArrowLeftIcon}
        tooltip={TOOLTIPS.output}
      />
      <StatRow
        label="Cache created"
        value={formatTokenCount(data.cache_creation)}
        icon={DiamondOutlineIcon}
        tooltip={TOOLTIPS.cacheCreated}
      />
      <StatRow
        label="Cache read"
        value={formatTokenCount(data.cache_read)}
        icon={DiamondFilledIcon}
        tooltip={TOOLTIPS.cacheRead}
      />
    </CardWrapper>
  );
}
